# Generated by Django 3.2.13 on 2023-05-21 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualTales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='paragraph',
        ),
        migrations.DeleteModel(
            name='Paragraph',
        ),
        migrations.DeleteModel(
            name='Prompt',
        ),
        migrations.DeleteModel(
            name='Story',
        ),
    ]
